import type { Metadata } from "next";
import {NextIntlClientProvider} from 'next-intl';
import {hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import Navbar from "../components/Navbar";
import "../globals.css";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};
 
export default async function RootLayout({children,params}: Props) {
 const {locale} = await params;
    const messages = await getMessages();

 if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
    return (
    <html lang={locale}>
      <body className="bg-white text-gray-900 dark:bg-gray-900 dark:text-white transition-colors duration-300">
        <NextIntlClientProvider locale={locale} messages={messages}>
                    <Navbar />

          {children}</NextIntlClientProvider>
      </body>
    </html>
  );
}